/**
 * @file servo.h
 * @brief Simple STM32 HAL servo motor control library.
 *
 * This library provides a small abstraction layer to control a SG90 servo
 * using a PWM channel generated by an STM32 timer.
 *
 * The timer and PWM channel must be configured previously in STM32CubeMX.
 * This library does not configure GPIO, timer prescaler, timer period, or
 * alternate function pins. It only starts/stops the PWM and writes the compare
 * value associated with the desired servo angle.
 *
 * @note This implementation assumes a timer configuration where the compare
 *       value range from @ref SERVO_MIN_PERIOD to @ref SERVO_MAX_PERIOD maps
 *       linearly to the servo angle range from 0 to 180 degrees.
 */

#ifndef SERVO_H
#define SERVO_H

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/**
 * @brief Minimum compare value used for 0 degrees.
 *
 * This value is written to the timer CCR register when the servo angle is 0.
 * It depends on the PWM timer configuration generated by STM32CubeMX.
 */
#define SERVO_MIN_PERIOD    60U

/**
 * @brief Maximum compare value used for 180 degrees.
 *
 * This value is written to the timer CCR register when the servo angle is 180.
 * It depends on the PWM timer configuration generated by STM32CubeMX.
 */
#define SERVO_MAX_PERIOD    240U

/**
 * @brief Maximum servo angle supported by this library.
 */
#define SERVO_MAX_ANGLE     180U

/**
 * @brief Servo object structure.
 *
 * This structure stores the STM32 HAL timer handle, the PWM channel used by
 * the servo, and the compare value range used to map angles to PWM pulses.
 */
typedef struct
{
    TIM_HandleTypeDef *htim;  /**< Pointer to the HAL timer handle. */
    uint32_t channel;         /**< Timer PWM channel, for example TIM_CHANNEL_1. */
    uint16_t min_period;      /**< Compare value associated with 0 degrees. */
    uint16_t max_period;      /**< Compare value associated with 180 degrees. */

} Servo_t;

/**
 * @brief Initializes a servo object.
 *
 * This function only initializes the software object. The timer and PWM channel
 * must already be configured by STM32CubeMX.
 *
 * @param servo Pointer to the servo object.
 * @param htim Pointer to the HAL timer handle.
 * @param channel Timer PWM channel used by the servo.
 */
void Servo_Init(Servo_t *servo, TIM_HandleTypeDef *htim, uint32_t channel);

/**
 * @brief Starts the PWM signal used by the servo.
 *
 * Internally, this function calls HAL_TIM_PWM_Start().
 *
 * @param servo Pointer to the servo object.
 * @return HAL status.
 * @retval HAL_OK PWM started successfully.
 * @retval HAL_ERROR Invalid servo object or HAL start error.
 */
HAL_StatusTypeDef Servo_Start(Servo_t *servo);

/**
 * @brief Stops the PWM signal used by the servo.
 *
 * Internally, this function calls HAL_TIM_PWM_Stop().
 *
 * @param servo Pointer to the servo object.
 * @return HAL status.
 * @retval HAL_OK PWM stopped successfully.
 * @retval HAL_ERROR Invalid servo object or HAL stop error.
 */
HAL_StatusTypeDef Servo_Stop(Servo_t *servo);

/**
 * @brief Sets the servo angle.
 *
 * The angle is converted linearly to a timer compare value between
 * @ref SERVO_MIN_PERIOD and @ref SERVO_MAX_PERIOD.
 *
 * Values greater than @ref SERVO_MAX_ANGLE are saturated to
 * @ref SERVO_MAX_ANGLE.
 *
 * @param servo Pointer to the servo object.
 * @param angle Desired angle in degrees, from 0 to 180.
 */
void Servo_SetAngle(Servo_t *servo, uint8_t angle);

#ifdef __cplusplus
}
#endif

#endif /* SERVO_H */
